import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/layouts/shared/Navbar";

const text = Nunito({
  subsets: ["latin"],
  weight: ["400", "600", "1000"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${text.className} text-balance bg-light text-dark`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
